version: "3"
services:
  web:
    build: ./api
    restart: always
    volumes:
      - ./api/src:/api
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
          max-size: "2m"
          max-file: "10"
