version: "3"
services:


  web:
    build: ./api
    restart: always
    volumes:
      - ./api/src:/api
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
          max-size: "2m"
          max-file: "10"
    depends_on:
      - "postgres"
    environment:
      # параметры подключения к бд
      DB_USER: dbuser
      DB_PASSWORD: dbpassword
      DB_NAME: transactions

      # параметры начального пользователя
      USER_EMAIL: root@localhost
      USER_PASSWORD: 1234
      USER_BALANCE: 1.234
      USER_CURRENCY: BTC


  postgres:
    image: postgres:12.1-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
    expose:
      - "5432"
    environment:
      # параметры для инициализации бд
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: transactions
